-- 0059_playback_ceiling: a per-User Playback ceiling — how a Title may play, as
-- opposed to whether it exists (ADR-0054 §2, .scratch/linked-servers issue 02).
--
-- Three columns beside rating_ceiling, because they are the same KIND of thing:
-- something the Server says about a User that every handler already enforces
-- through access.Service.Resolve. rating_ceiling caps WHAT a User may see;
-- these cap HOW it reaches them.
--
--   max_resolution  a ceiling token from the negotiation vocabulary ('720p',
--                   '1080p', '2160p'), clamped into the session's Constraints.
--   max_bitrate     bits/sec, clamped the same way.
--   max_streams     the most concurrent Playback sessions this User may hold.
--
-- All three are NULLABLE and unset by default = UNCAPPED, so this migration
-- changes nothing about any existing User: every row keeps NULL and every
-- negotiation clamps against nothing. A ceiling never hides a Title — a 4K-only
-- File under a 1080p ceiling transcodes down under the Server's own governance
-- (ADR-0009) rather than vanishing from the catalog.
--
-- Nullable rather than `DEFAULT 0`: "no opinion" and "zero" are different
-- statements, and only NULL says the first. The read path collapses NULL to the
-- zero value anyway (COALESCE in PlaybackCeilingForUser), so the distinction
-- costs nothing and keeps a future "0 means refuse all playback" open.
--
-- No CHECK on max_resolution's vocabulary: the settable set is validated in
-- access.Service.SetPlaybackCeiling (as the Rating ceiling's ladder is), and a
-- token the negotiator does not recognize already reads as "uncapped" — a
-- CHECK here would only duplicate that rule in a place SQLite cannot alter
-- later without another table rebuild.
--
-- Plain ADD COLUMNs: unlike 0058 (which had to rebuild `users` to alter a
-- CHECK), adding nullable columns with no default is an in-place SQLite
-- operation, so the table, its constraints and every index stay as they are.
ALTER TABLE users ADD COLUMN max_resolution TEXT;
ALTER TABLE users ADD COLUMN max_bitrate INTEGER;
ALTER TABLE users ADD COLUMN max_streams INTEGER;
