package auth

import (
	"errors"
	"log"
	"time"

	"github.com/goozakdev/obelo-server/internal/store"
)

// Session stream tokens (.scratch/session-stream-tokens): the server's SECOND
// expiring credential kind, after the device authorization grant (ADR-0036).
//
// A stream token authorises the media artifacts of exactly ONE Playback session
// and nothing else — not the JSON API, not another session, not another User's
// session, not a mutation. It exists because a whole class of player cannot
// present either credential the media routes accept today: it hands the URL to
// somebody else and lets THEM fetch. AirPlay video is the motivating case (the
// receiver is a television running software we do not own), but "a player that
// delegates the fetch" is a category, not one feature.
//
// It is a poll-secret-class value, on the deviceCode side of the line ADR-0036
// drew: 256 bits of CSPRNG, generated by the same newToken, stored only as a
// hash, and NEVER logged or placed in an error envelope. There is deliberately no
// short display sibling — nothing here is read by a human, so a userCode analogue
// would only be a second thing to confuse with the secret.

// streamTokenTTL is how long a minted stream token stays usable.
//
// The number is bounded from both sides by machinery that already exists, and the
// bounds do not meet in the middle by accident:
//
//   - It must not die before its session. A session stays alive as long as it is
//     being watched — every progress report (~10-15s), manifest, and segment fetch
//     Touches it, and only config.DefaultSessionIdleTimeout (90s) of TOTAL silence
//     lets the reaper end it. An actively-watched session therefore lasts as long
//     as the sitting does, and a token that expires mid-film is a television going
//     black for no reason the viewer can act on. The receiver cannot re-mint: it
//     was handed a URL, and AVFoundation will not go back for another one.
//
//   - It must not outlive its usefulness. It cannot be shortened by leaning on
//     re-minting (see above), so the ceiling is "one sitting, generously" — long
//     enough for a feature-length Title with pauses, short enough that a token
//     logged on somebody's television is dead by the next day.
//
//   - Revocation, not expiry, is the real control. The session-ended cascade
//     (RevokeStreamTokens, fired by DELETE /sessions/{id} AND by the idle reaper)
//     deletes a session's tokens within SessionIdleTimeout + SessionReapInterval —
//     90s + 30s = a two-minute worst case — of the last byte fetched. This TTL only
//     binds where that cascade cannot run at all: after a restart, when the
//     in-memory session map is gone but the SQLite rows remain.
//
// Four hours is the smallest round span that clears the longest Title anyone
// plausibly plays in one sitting, and it is exactly 120 of the reaper's two-minute
// worst-case windows — which is the honest way to read it: the reaper gets 120
// chances to revoke this token before its expiry ever matters.
const streamTokenTTL = 4 * time.Hour

// StreamTokenGrant is what a mint returns: the raw secret (handed out exactly
// once, since only its hash is stored) and when it dies. ExpiresIn is the same
// instant as a duration, for a client scheduling a re-mint.
type StreamTokenGrant struct {
	Token     string
	ExpiresAt time.Time
	ExpiresIn time.Duration
}

// MintStreamToken issues a stream token for (sessionID, userID). The CALLER has
// already established that the session exists and belongs to userID — this
// package knows nothing about Playback sessions, and the ownership check plus its
// 404-not-403 posture belongs with the handler that can see them.
//
// It sweeps expired rows first, on the same request-time trigger
// StartDeviceAuth sweeps device-auth rows: no background goroutine to own, and
// the only moment the table's size can matter is the moment a row is added.
func (s *Service) MintStreamToken(sessionID, userID string) (StreamTokenGrant, error) {
	if sessionID == "" || userID == "" {
		return StreamTokenGrant{}, errors.New("auth: sessionId and userId are required to mint a stream token")
	}
	now := s.now()
	if err := s.store.DeleteExpiredStreamTokens(formatTime(now)); err != nil {
		return StreamTokenGrant{}, err
	}
	raw, err := newStreamToken()
	if err != nil {
		return StreamTokenGrant{}, err
	}
	expires := now.Add(streamTokenTTL)
	if err := s.store.InsertStreamToken(store.StreamToken{
		TokenHash: hashToken(raw),
		SessionID: sessionID,
		UserID:    userID,
		CreatedAt: formatTime(now),
		ExpiresAt: formatTime(expires),
	}); err != nil {
		return StreamTokenGrant{}, err
	}
	return StreamTokenGrant{Token: raw, ExpiresAt: expires, ExpiresIn: streamTokenTTL}, nil
}

// VerifyStreamToken answers the one question the media transport asks: may this
// raw token fetch THIS session's bytes, and as whom? It checks both halves — that
// the token is live and that it belongs to sessionID — in a single lookup whose
// expiry predicate is SQL, never a Go comparison against a row already in hand.
//
// A token that authenticates but names a different session is ok=false, exactly
// like one that never existed or has expired: the caller answers 404 for all of
// them and must not tell them apart on the wire.
//
// It returns no error on purpose. There is nothing a transport could usefully do
// with one but 404, and an error return invites a handler to render it — which is
// how a secret ends up in an envelope. A genuine store fault is logged here (the
// token never is) and reported as a refusal, which fails closed.
func (s *Service) VerifyStreamToken(raw string, sessionID string) (userID string, ok bool) {
	if raw == "" || sessionID == "" {
		return "", false
	}
	t, err := s.store.LiveStreamTokenForSession(hashToken(raw), sessionID, formatTime(s.now()))
	if err != nil {
		logStreamTokenLookupError(err)
		return "", false
	}
	return t.UserID, true
}

// ResolveStreamToken maps a raw token to the session and User it authorises,
// without being told which session to expect. It is the entry point for the
// path-carried media routes, where the token IS the session identifier (the URL
// carries no session id, so there is nothing to check it against yet); the
// resolved session id then drives the ordinary owner-checked handlers.
//
// Same refusal discipline as VerifyStreamToken: unknown, expired, and revoked are
// one indistinguishable ok=false, and no error escapes for a handler to render.
func (s *Service) ResolveStreamToken(raw string) (sessionID, userID string, ok bool) {
	if raw == "" {
		return "", "", false
	}
	t, err := s.store.LiveStreamToken(hashToken(raw), formatTime(s.now()))
	if err != nil {
		logStreamTokenLookupError(err)
		return "", "", false
	}
	return t.SessionID, t.UserID, true
}

// RevokeStreamTokens deletes every stream token minted for a session. It is the
// revocation the feature promises, and it is driven by the session-ended signal
// so BOTH ways a session can end — the clean DELETE /sessions/{id} and the idle
// reaper — revoke through one path rather than two that can drift.
//
// Idempotent: a session that never minted a token revokes nothing and succeeds.
func (s *Service) RevokeStreamTokens(sessionID string) error {
	if sessionID == "" {
		return nil
	}
	return s.store.DeleteStreamTokensForSession(sessionID)
}

// SweepStreamTokens removes aged-out rows. Mint already does this; the method
// exists so a caller with no reason to mint (a maintenance path, a test) can
// drive the sweep without inventing one.
func (s *Service) SweepStreamTokens() error {
	return s.store.DeleteExpiredStreamTokens(formatTime(s.now()))
}

// newStreamToken returns the raw secret: 256 bits of CSPRNG in URL-safe base64,
// the same generator as a session token and a device code.
//
// URL-SAFE is load-bearing rather than tidy here. This value goes in a URL PATH
// segment (/api/v1/stream/{streamToken}/...), so it must survive path encoding
// with no escaping — base64.RawURLEncoding emits only [A-Za-z0-9_-], every one of
// which is an unreserved or sub-delims character a path segment carries verbatim.
// Standard base64 would emit '+' and '/', and the '/' alone would split the
// segment and break the route.
func newStreamToken() (string, error) {
	return newToken()
}

// logStreamTokenLookupError reports a GENUINE store fault behind a token lookup.
// A not-found (unknown, revoked, or expired token) is the ordinary answer and is
// silent — logging it would turn every probe into a log line. The raw token is
// never an argument here and must never become one: it is in a URL, and this is
// the closest place to that URL where a secret could be written down.
func logStreamTokenLookupError(err error) {
	if err == nil || errors.Is(err, store.ErrNotFound) {
		return
	}
	log.Printf("obelo: auth: stream token lookup failed: %v", err)
}
